### ISSUE TITLE
Create config file, and pull API URLs into default configuration

### ISSUE THREAD

**Issue by kitplummer** [ion-channel/lowendinsight#24]
Move all of the URLs to a configuration, use a default that is installed with the gem.

**Comment by matthewkmayer** [comment]
@kitplummer do you have an example of a default that's installed with the gem?  Or was the work done to provide internal defaults sufficient?

**Comment by kitplummer** [comment]
Nope, this is the first gem.  But, I'd imagine will deploy the config with Salt to instances that are using LEI.

**Comment by matthewkmayer** [comment]
I think this is all done!

**Comment by kitplummer** [comment]
Probably just need to update the README?  With the config file example, and location information?

**Comment by matthewkmayer** [comment]
README all done!
